services:
  client:
    container_name: icdrc_frontend
    image: app1
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
    env_file:
      - ./frontend/.env
    environment:
      - NEXTAUTH_URL=http://77.37.45.141:3000
      - NEXTAUTH_SECRET=hMVQySmVjbrzps89s+Ro4SGGSmKpjF8Ox5XI7VAs2J0=

  dashboard:
    container_name: icdrc_dashboard
    image: app2
    build: ./dashboard
    ports:
      - "3001:3001"
    depends_on:
      - backend
    restart: always
    env_file:
      - ./dashboard/.env

  backend:
    container_name: icdrc_backend
    build: ./backend
    restart: always
    depends_on:
      - redis
    env_file:
      - ./backend/.env
    ports:
      - "7000:7000"

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
