import {
    ArrowLeftToLine,
    ArrowRightToLine, ArrowUpDown, BotMessageSquare,
    CreditCard, FileSearch2, Gavel, Handshake, Images, LayoutDashboard, ListFilter, Loader2,
    Mail, MessageSquareText, MessagesSquare, MoreHorizontal, MoreVertical, PackageSearch, Pencil, PlusCircle,
    Rss,
    Settings,
    SquareUser,
    Star,
    Trash,
    UserCog,
    Users,
    UserSearch,
    X
} from "lucide-react";

export const Icons = {
    chat: MessageSquareText,
    media: Images,
    testimonial: Star,
    team: SquareUser,
    individual: UserSearch,
    organisational: PackageSearch,
    mediation: Gavel,
    settings: Settings,
    edit: Pencil,
    caseStudy: FileSearch2,
    subscription: Users,
    partner: Handshake,
    bot: BotMessageSquare,
    payment: CreditCard,
    delete: Trash,
    add: PlusCircle,
    close: X,
    sort: ArrowUpDown,
    filter: ListFilter,
    horizontalDot: MoreHorizontal,
    verticalDot: MoreVertical,
    loader: Loader2,
    home: LayoutDashboard,
    user: UserCog,
    contact: Mail,
    blog: Rss,
    asideClose: ArrowLeftToLine,
    asideOpen: ArrowRightToLine,
}
