import {
    ArrowLeftToLine,
    ArrowRightToLine, ArrowUpDown, BotMessageSquare,
    CreditCard, Edit, Gift, Handshake, Home, ListFilter, Loader2,
    Mail, MoreHorizontal, MoreVertical, NotebookPen, Pencil, PlusCircle,
    Settings, ShieldQuestion, SquareKanban,
    Trash, User,
    UsersRound, X
} from "lucide-react";

export const Icons = {
    team: UsersRound,
    individual: SquareKanban,
    organisational: ShieldQuestion,
    settings: Settings,
    edit: Pencil,
    caseStudy: NotebookPen,
    subscription: Gift,
    partner: Handshake,
    bot: BotMessageSquare,
    payment: CreditCard,
    delete: Trash,
    add: PlusCircle,
    close: X,
    sort: ArrowUpDown,
    filter: ListFilter,
    horizontalDot: MoreHorizontal,
    verticalDot: MoreVertical,
    loader: Loader2,
    home: Home,
    user: User,
    contact: Mail,
    blog: Edit,
    asideClose: ArrowLeftToLine,
    asideOpen: ArrowRightToLine,
}
