name: Build and Deploy

on:
  push:
    branches:
      - master

env:
  MONGO_URL: ${{ secrets.MONGO_URL }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install dependencies and run tests for the client application
      - name: Install Client
        working-directory: ./frontend
        run: |
          npm install
         

      # Install dependencies, export environment variables, and run tests for the server application
      - name: Install Server
        working-directory: ./backend
        run: |
          npm install
          export MONGO_URL=$MONGO_URL
          export JWT_SECRET=$JWT_SECRET
        
      # Build a Docker image for the client application
      - name: Build Client Docker Image
        working-directory: ./frontend
        run: |
          docker build -t abhishekdev45/icdrc-client:latest .
          docker push abhishekdev45/icdrc-client:latest 

      # Build a Docker image for the server application
      - name: Build Server Docker Image
        working-directory: ./backend
        run: |
           docker build -t abhishekdev45/icdrc-server:latest .
           docker push abhishekdev45/icdrc-server:latest

      # SSH into server and deploy with Docker Compose
      - name: Deploy on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
            cd /var/www/ICDRC/
            docker-compose down
            docker-compose pull
            docker-compose up -d

            
